version: "3.4"

services:
  swaye:
    container_name: ipseity-cms
    user: $DOCKER_USER
    restart: always
    image: swaye/php:8.0-apache
    #build: ./
    volumes:
      - "./src:/var/www/html"
      - "./.env:/var/www/html/.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ipseity-cms.rule=Host(`cms.chatsw.kitechltd.com`)"
    networks:
      - default
    environment:
      APP_NAME: $APP_NAME
      APP_ENV: $APP_ENV
      APP_KEY: $APP_KEY
      DB_HOST: $DB_HOST
      DB_DATABASE: $DB_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD

networks:
  default:
    external: true
    name: proxy_default
