version: '3.9'
services:
  postgres:
    container_name: ipseity-postgres
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_USER: ipseity
      POSTGRES_PASSWORD: ipseity
      POSTGRES_DB: ipseity
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data:
