version: "3.5"

services:
  db:
    image: mariadb:10.5.8
    container_name: db
    volumes:
      - ./run/var:/etc/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

  lumen-portfolio-api:
    image: swaye/php-7.4-apache
    container_name: lumen-portfolio-api
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      API_TOKEN: ${API_TOKEN}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    ports:
      - ${HOST_PORT}:80
    networks:
      backend:
        aliases:
          - lumen-portfolio-api
    command: ["apache2-foreground"]
networks:
  backend:
    name: backend-network
